require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25
