require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
